apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: setup
  template:
    metadata:
      labels:
        app: setup
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus:latest
          env:
          - name: MAX_HEAP
            value: "800m"
          - name: MIN_HEAP
            value: "300m"
          resources:
            limits:
              memory: "6Gi"
              cpu: "1200m"
            requests:
              memory: "4Gi"
              cpu: "800m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-vol
              mountPath: /setup
      volumes:
        - name: nexus-vol
          emptyDir: {}